// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuiXPyC9FqJfa_D--p_GdzrJqG8xBrCw',
    appId: '1:329564336763:web:f0664c4d00dd7add0868de',
    messagingSenderId: '329564336763',
    projectId: 'projectstoredata-f7030',
    authDomain: 'projectstoredata-f7030.firebaseapp.com',
    storageBucket: 'projectstoredata-f7030.firebasestorage.app',
    measurementId: 'G-5HBD13211X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGNmrHMTUv0pwLFHiCaJTxTdNqUmbVJs',
    appId: '1:329564336763:android:02c7f338a4e10d1d0868de',
    messagingSenderId: '329564336763',
    projectId: 'projectstoredata-f7030',
    storageBucket: 'projectstoredata-f7030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdPP-v_F4nrF9VKMx9fAr-ZSnW6wQPX7Y',
    appId: '1:329564336763:ios:5c76d06c76a7cb100868de',
    messagingSenderId: '329564336763',
    projectId: 'projectstoredata-f7030',
    storageBucket: 'projectstoredata-f7030.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );
}
